### ISSUE TITLE
Spark module not working in dev branch

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/appmod-blueprints#222]
Using dev branch the module for SparkApplication doesn't work
Gives the following error
```
 failed to run spark-submit for SparkApplication argo/spark-pi-spark-job-module5: WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int) WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release 25/04/15 01:49:44 WARN NativeCodeLoader: Unable to load native-hadoop
```

The problem shows up only in hub cluster running EKS 1.32 with Auto Mode and BottleRocket nodes, spark works fine in dev cluster which is not using EKS Auto and using EKS 1.30

I also tested with simpler spark app and using latest spark operator version still failed
```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.5
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar
  arguments:
  - "5000"
  sparkVersion: 3.5.5
  driver:
    labels:
      version: 3.5.5
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.5
    instances: 1
    cores: 1
    memory: 512m
```
